#lang eopl

(define (sort/predicate pred lst)
  (define (insert x sorted)
    (if (null? sorted)
        (list x)
        (if (pred x (car sorted))
            (cons x sorted)
            (cons (car sorted) (insert x (cdr sorted))))))
  (define (isort sorted unsorted)
    (if (null? unsorted)
        sorted
        (isort (insert (car unsorted) sorted) (cdr unsorted))))
  (isort '() lst))

(eopl:pretty-print (sort/predicate < '(8 2 5 2 3)))
(eopl:pretty-print (sort/predicate > '(8 2 5 2 3)))
(eopl:pretty-print (sort/predicate > '()))
(eopl:pretty-print (sort/predicate > '(1)))
(eopl:pretty-print (sort/predicate > '(1 2)))
(eopl:pretty-print (sort/predicate > '(2 1)))
(eopl:pretty-print (sort/predicate > '(1 2 3)))
(eopl:pretty-print (sort/predicate > '(1 3 2)))
(eopl:pretty-print (sort/predicate > '(2 1 3)))
(eopl:pretty-print (sort/predicate > '(2 3 1)))
(eopl:pretty-print (sort/predicate > '(3 1 2)))
(eopl:pretty-print (sort/predicate > '(3 2 1)))